name: movies_modularised
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  powers: ^0.1.0
  pedantic: ^1.9.2
  http: ^0.12.2
  built_value: ^7.1.0
  built_collection: ^4.3.2
  flutter_redux: ^0.7.0
  redux: ^4.0.0+3
  freezed_annotation: ^0.12.0
  flutter_config: ^1.0.8
  flutter_staggered_grid_view: ^0.3.3
  redux_epics: ^0.14.0
  rxdart: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  built_value_generator: ^7.1.0
  freezed: any
  analyzer: any

flutter:
  uses-material-design: true

